### ISSUE TITLE
Change to PDL's PDL_INCLUDE breaks P::D::P build for PDL 2.008

### ISSUE THREAD

**Issue by d-lamb** [run4flat/PDL-Drawing-Prima#30]
Hi David

Because of this commit (see Basic/Core/Dev.pm) to be part of PDL-2.008, http://sourceforge.net/p/pdl/code/ci/d7172dcfa2da412e5e28894a9df96ec602adc7ac/ PDL-Drawing-Prima does not build (on my OS X Yosemite compiling with clang) because it can not find pdl.h.  This is because the location of pdl.h is -Included with double quotes now:

-I"/Users/derek/local/lib.../PDL/Core" instead of -I/Users/derek/....PDL/Core

You can fix this in Build.PL by adding another regex after the the first '$inc =~ s/-I//g;' 

$inc =~ s/\"//g;

Sorry this is not a pull request.  Seemed silly to fork and pull request for a one-line change.

**Comment by run4flat** [comment]
Hey Derek, thanks for reporting this. I added a line that should fix this, I believe.

In the future, when you have a one-line fix like that, github has an interface that lets you edit the file in your browser and create a fork in your own account. You don't even need to pull the repository to your own machine and create your own fork.

**Comment by fantasma13** [comment]
Hi David,

I have exactly this issue in v0.10. Did you (not) release the fix by any chance?
Ingo

**Comment by run4flat** [comment]
No, I've not released it yet. I've been meaning to test things out before pushing the latest version to CPAN. I'll try to get to that soon, maybe today.

**Comment by devel-chm** [comment]
Was this fixed code released?  I just tried to install PDL-Drawing-Prima-0.10 and had the same egregious extra "s leading to the build failure.  Hand correcting in the _build folder to remove the extra quotes allowed the build to complete.

**Comment by fantasma13** [comment]
No, it's not released yet, unfortunately. That means manual editing Build.PL whenever you need to install.

**Comment by devel-chm** [comment]
It would be nice if PDL::Graphics::Prima could be working for the upcoming
PDL-2.014 release?

**Comment by run4flat** [comment]
I have released the latest PDL::Drawing::Prima to CPAN. It seems to work fine for me, so I would appreciate any feedback on failures.

Thanks!

**Comment by devel-chm** [comment]
Yay, works out of the box on cygwin+PDL-2.014!

Thanks,
Chris
