### ISSUE TITLE
PDL-2.016 breaks P-D-P-0.11

### ISSUE THREAD

**Issue by sisyphus** [run4flat/PDL-Drawing-Prima#32]
As of PDL-2.016 it becomes necessary to add "pp_done();" to the very end of lib/PDL/Drawing/Prima/Utils.pm.PL as PP.pm no longer does that for us.

Cheers,
Rob

**Comment by mohawk2** [comment]
This was done in https://github.com/run4flat/PDL-Drawing-Prima/commit/0962cf3738f901c3abc7b8ee1e2c49413f8301c8
