### ISSUE TITLE
Prima changed fillWinding to fillMode

### ISSUE THREAD

**Issue by fantasma13** [run4flat/PDL-Drawing-Prima#33]
In Prima 1.56, the above change was introduced which causes P-D-P to no longer build. A simple search and replace for the two terms seems to work, how to make P-D-P smart enough to base code on Prima version is beyond me (my available time) to figure out, since properties are constructed from pod (doc_string). A simple if - else with two versions of the doc_string did not do it (or I messed it up along the way).

**Comment by mohawk2** [comment]
This is fixed in https://github.com/run4flat/PDL-Drawing-Prima/commit/66a903a67a2f3f4652a08d7ca85b05ec27baf0f7

**Comment by run4flat** [comment]
Thank you, this was fixed in the development version with the commit mentioned earlier. That development version has finally been released under v0.13. Sorry for the delay in pushing out the fix!
