### ISSUE TITLE
Errors of compiling with PDL-2.057

### ISSUE THREAD

**Issue by YuryPakhomov** [run4flat/PDL-Drawing-Prima#37]
Building PDL-Drawing-Prima
cc -I/usr/local/lib64/perl5/PDL/Core -I/usr/local/lib64/perl5/Prima/../Prima/CORE -I/usr/local/lib64/perl5/Prima/../Prima/CORE/generic -I/usr/include/fribidi -I/usr/include/libxml2 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/lib64/perl5/CORE -DVERSION="0.12" -DXS_VERSION="0.12" -fPIC -c -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -fPIC -o lib/PDL/Drawing/Prima.o lib/PDL/Drawing/Prima.c
lib/PDL/Drawing/Prima.pm.PL: In function 'pdl_prima_fillpolys_readdata':
lib/PDL/Drawing/Prima.pm.PL:950:59: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  950 |                 }
      |                                                           ^ 
lib/PDL/Drawing/Prima.pm.PL:953:47: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  953 |                         curr_$singular = SvIV(*(hv_fetch(arg_hash_hv, \"$singular\", $sing_length, 0)));
      |                                               ^~
lib/PDL/Drawing/Prima.pm.PL:955:20: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
  955 |                 }\n");
      |                    ^~
lib/PDL/Drawing/Prima.pm.PL:1434:31: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1434 |                          * pattern is much simpler. */
      |                               ^~
lib/PDL/Drawing/Prima.pm.PL:1448:6: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1448 | $pars_args_for{splinePrecisions} = 'int splinePrecisions()';
      |      ^~
lib/PDL/Drawing/Prima.pm.PL:950:59: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  950 |                 }
      |                                                           ^ 
lib/PDL/Drawing/Prima.pm.PL:953:47: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  953 |                         curr_$singular = SvIV(*(hv_fetch(arg_hash_hv, \"$singular\", $sing_length, 0)));
      |                                               ^~
lib/PDL/Drawing/Prima.pm.PL:955:20: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
  955 |                 }\n");
      |                    ^~
lib/PDL/Drawing/Prima.pm.PL:1434:31: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1434 |                          * pattern is much simpler. */
      |                               ^~
lib/PDL/Drawing/Prima.pm.PL:1448:6: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1448 | $pars_args_for{splinePrecisions} = 'int splinePrecisions()';
      |      ^~
lib/PDL/Drawing/Prima.pm.PL: In function 'pdl_prima_symbols_readdata':
lib/PDL/Drawing/Prima.pm.PL:950:59: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  950 |                 }
      |                                                           ^ 
lib/PDL/Drawing/Prima.pm.PL:953:47: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  953 |                         curr_$singular = SvIV(*(hv_fetch(arg_hash_hv, \"$singular\", $sing_length, 0)));
      |                                               ^~
lib/PDL/Drawing/Prima.pm.PL:955:20: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
  955 |                 }\n");
      |                    ^~
lib/PDL/Drawing/Prima.pm.PL:1434:31: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1434 |                          * pattern is much simpler. */
      |                               ^~
lib/PDL/Drawing/Prima.pm.PL:1448:6: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1448 | $pars_args_for{splinePrecisions} = 'int splinePrecisions()';
      |      ^~
lib/PDL/Drawing/Prima.pm.PL:950:59: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  950 |                 }
      |                                                           ^ 
lib/PDL/Drawing/Prima.pm.PL:953:47: error: 'struct _Drawable_vmt' has no member named 'get_fillWinding'
  953 |                         curr_$singular = SvIV(*(hv_fetch(arg_hash_hv, \"$singular\", $sing_length, 0)));
      |                                               ^~
lib/PDL/Drawing/Prima.pm.PL:955:20: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
  955 |                 }\n");
      |                    ^~
lib/PDL/Drawing/Prima.pm.PL:1434:31: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1434 |                          * pattern is much simpler. */
      |                               ^~
lib/PDL/Drawing/Prima.pm.PL:1448:6: error: 'struct _Drawable_vmt' has no member named 'set_fillWinding'
 1448 | $pars_args_for{splinePrecisions} = 'int splinePrecisions()';
      |      ^~
error building lib/PDL/Drawing/Prima.o from 'lib/PDL/Drawing/Prima.c' at /usr/share/perl5/ExtUtils/CBuilder/Base.pm line 185.

**Comment by YuryPakhomov** [comment]
Slackware64, last update 18.08.2021
Current packages:
perl-5.34.0-x86_64-1 
gcc-11.2.0_multilib-x86_64-1alien
glibc-2.33_multilib-x86_64-4alien
perl-pdl-2.057-x86_64-1
perl-prima-1.62-x86_64-1

**Comment by YuryPakhomov** [comment]
Git version 12.01_01 is work.

**Comment by run4flat** [comment]
Thank you for this bug report, as well as the follow-up indicating that the dev version worked. I just released the development work as PDL::Drawing::Prima (v0.13) so now hopefully it will compile for anybody who wants to just install it off of CPAN. Closing for now.
